name: Unity QA Automation Regression Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  run-regression-tests:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Execute Unity QA Master Pipeline
        # shell: cmd 설정을 넣어 윈도우 배치 파일이 100% 안전하게 구동되도록 박아버립니다
        shell: cmd
        run: |
          cd /d D:\funity\Test1
          call alt-tests\run_alt_ci_pipeline.bat